Add a logo
SciTools/ncdata pull request #75
Opened 2024-05-31 11:58 UTC by trexfeathers

I used Microsoft Office to draw these - hence the originals are in a `.xlsx` file. This is not ideal, but it would take much longer to work out how to achieve the same with PyVista / manual drawing / whatever.

Also not ideal is PNG rather than SVG format. Office can produce SVGs, but when 3D perspective is applied (as in this case) the image is actually just a raster underneath.

2024-05-31 11:59 UTC, trexfeathers commented on docs/conf.py
> +        "text": "ncdata documentation",
The title previously automatically included the version, too. I expect we could bring this back if desired.

2024-06-03 09:22 UTC, pp-mo commented
This is great stuff !
And very timely, since I'm hoping to push along proper docs pages quite soon.

Thanks for taking the trouble -- I'm going to add you as a contributor / maintainer (hopefully will unblock future RTD runs ?)

2024-06-03 09:27 UTC, pp-mo requested changes
At the very worst, this is a great start !

Can you inject this into the main-page README also ?
I think that will improve the look of the entire project, 
though I suspect it will make it even more desirable to write a better oneline project summary

2024-06-03 09:30 UTC, trexfeathers commented
> At the very worst, this is a great start !
> 
> Can you inject this into the main-page README also ? I think that will improve the look of the entire project, though I suspect it will make it even more desirable to write a better oneline project summary

I think I have done this (unless I am misunderstanding). [ncdata/README.md at `5395b61` · pp-mo/ncdata (github.com)](https://github.com/pp-mo/ncdata/blob/5395b6119b3259a982e21841eb9814771ebcf4cc/README.md)

2024-06-03 10:47 UTC, pp-mo commented
> I think I have done this
OK I think I failed to understand this, because I stupidly followed the README link from the docs build instead of looking at the README as modified here !

Definitely good enough for now, thanks @trexfeathers

2024-06-03 10:48 UTC, pp-mo approved these changes

2024-06-03 10:49 UTC, pp-mo commented on docs/conf.py
> +        "text": "ncdata documentation",
I'm not worried about this.
The version isn't well handed in the current RTD builds anyway.

2024-06-03 10:49 UTC, merged